import type { Metadata } from 'next';

import '@/app/globals.scss';

import Header from '@/app/components/layout/Header/Header';
import Footer from '@/app/components/layout/Footer/Footer';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='en'>
      <body>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
